In [2]:
print('EXAMPLE 1')
import scipy as sc
import numpy as np
array1=np.array(([1,2,3]))
print(array1)

EXAMPLE 1
[1 2 3]


In [19]:
print('EXAMPLE 2')
array2=np.linspace(0,10,5)
print(array2,'\n')
array22=np.linspace(0,1,3)
print(array22,'\n')

EXAMPLE 2
[ 0.   2.5  5.   7.5 10. ] 

[0.  0.5 1. ] 



In [20]:
print('EXAPMLE 3')
array3=np.arange(0,10,1)
print(array3,'\n')
array4=np.arange(0,5,0.5)
print(array4,'\n')
array44=np.arange(5)
print(array44,'\n')
print(np.arange(10),'\n')

EXAPMLE 3
[0 1 2 3 4 5 6 7 8 9] 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[0 1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 



In [21]:
print('EXAMPLE 4')
array5=np.zeros(5)
print(array5,'\n')
array6=np.ones(3)
print(array6,'\n')

EXAMPLE 4
[0. 0. 0. 0. 0.] 

[1. 1. 1.] 



In [22]:
print('EXAMPLE 5')
array7=np.linspace(-2,3,6)
print(array7,'\n')
print(array7+2,'\n')
print(array7-1,'\n')
print(array7*3,'\n')
print(array7/2,'\n')
print(array7**4,'\n')
print((array7+2)*5,'\n')
print(np.sin(array7),'\n')
print(np.cos(array7),'\n')

EXAMPLE 5
[-2. -1.  0.  1.  2.  3.] 

[0. 1. 2. 3. 4. 5.] 

[-3. -2. -1.  0.  1.  2.] 

[-6. -3.  0.  3.  6.  9.] 

[-1.  -0.5  0.   0.5  1.   1.5] 

[16.  1.  0.  1. 16. 81.] 

[ 0.  5. 10. 15. 20. 25.] 

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743  0.14112001] 

[-0.41614684  0.54030231  1.          0.54030231 -0.41614684 -0.9899925 ] 



In [23]:
print('EXAMPLE 6')
array8=np.array([10,20,30])
array9=np.array([50,60,70])
result1=array8+array9
print(result1,'\n')
print(array9-array8,'\n')
print(array8-array9,'\n')
print(array8*array9,'\n')
print(array9/array8,'\n')

EXAMPLE 6
[ 60  80 100] 

[40 40 40] 

[-40 -40 -40] 

[ 500 1200 2100] 

[5.         3.         2.33333333] 



In [3]:
print('EXAMPLE 7')
array10=np.array ([[1,2,3],[4,5,6]])
print(array10,'\n')
array11=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(array11,'\n')
                  

EXAMPLE 7
[[1 2 3]
 [4 5 6]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]] 



In [4]:
print('EXAMPLE 8')
array12=np.array([np.eye(3)])
print(array12,'\n')

EXAMPLE 8
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]] 



In [73]:
print('EXAMPLE 9')
array13=np.arange(8)
print(array13,'\n')
array14=np.reshape(array13,(2,4))
print(array14,'\n')
print(np.reshape(arange13,(4,2)),'\n')
print(np.reshape(np.arange(8),(4,2)),'\n')
print(np.reshape(array13,[2,5],'\n')

SyntaxError: unexpected EOF while parsing (<ipython-input-73-e95290c8ad62>, line 8)

In [36]:
print("EXAMPLE 10")
array15=np.array([[1,4,5],[2,3,6]])
print(array15,'\n')
print(array15+2,'\n')
print(array15-3,'\n')
print(array15*3,'\n')
print(2/array15**3,'\n')
print(np.cos(array15),'\n')

EXAMPLE 10
[[1 4 5]
 [2 3 6]] 

[[3 6 7]
 [4 5 8]] 

[[-2  1  2]
 [-1  0  3]] 

[[ 3 12 15]
 [ 6  9 18]] 

[[2.         0.03125    0.016     ]
 [0.25       0.07407407 0.00925926]] 

[[ 0.54030231 -0.65364362  0.28366219]
 [-0.41614684 -0.9899925   0.96017029]] 



In [33]:
print("EXAMPLE 11")
array16=np.array([[1.,2.,3.],[4.,5.,6.]])
print(array16,'\n')
array17=np.array([[-1.,-2.,-3.],[-4.,-5.,-6.]])
print(array17,'\n')
array16*array17
print(np.dot(array16,array17),'\n')

EXAMPLE 11


NameError: name 'np' is not defined

In [50]:
print("EXAMPLE 12")
array18=sc.rand(8)
print(np.array(np.reshape((array18),(2,4))),'\n')
array19=print(np.array(np.reshape((sc.rand(8)),(2,4))),'\n')

EXAMPLE 12


NameError: name 'sc' is not defined

In [45]:
print("EXAMPLE 13")
array20=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array20,'\n')
print(array20[0,:],'\n')
print(array20[1,:],'\n')
print(array20[2,:],'\n')

EXAMPLE 13
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[4 5 6] 

[7 8 9] 



In [46]:
print(array20[:,0],'\n')
print(array20[:,1],'\n')
print(array20[:,2],'\n')

[1 4 7] 

[2 5 8] 

[3 6 9] 



In [47]:
print(array20[0,:]*array20[:,0],'\n')
print(array20[0,0]*array20[0,:],'\n')


[ 1  8 21] 

[1 2 3] 



In [57]:
print(np.dot((array20[0,:]),(array20[:,0])),'\n')


30 



In [60]:
print(np.dot((array20[0,:]),np.array(np.reshape(array20[:,0],(3,1)))),'\n')

[30] 



In [61]:
print(array20,'\n')
print(array20*array20,'\n')
print(np.dot(array20,array20),'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] 



In [63]:
array21=np.arange(9).reshape((3,3))
print(array21,'\n')
array22=np.transpose(np.arange(3).reshape(1,3))
print(array22,'\n')
print(np.dot(array21,array22),'\n')
print(array21*array22,'\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0]
 [1]
 [2]] 

[[ 5]
 [14]
 [23]] 

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]] 

